### ISSUE TITLE
'NoneType' object has no attribute 'session'

### ISSUE THREAD

**Issue by galileoguzman** [Martlark/flask-serialize#28]
Hey guys,

I am having an issue with the implementation:

```
@users_blueprint.route('/user/profile', methods=['GET', 'PUT'])
@login_required
def users():
    return User.get_delete_put_post(request.current_user)
```

GET method: works perfectly
PUT method: When I hit it, it fails

**Comment by Martlark** [comment]
This will be caused by not setting the db attribute of the mixin.  As per the documentation example.


    # required to set class var db for writing to a database
    from app import db

    FlaskSerializeMixin.db = db

**Comment by Martlark** [comment]
> Hey guys,
> 
> I am having an issue with the implementation:
> 
> ```
> @users_blueprint.route('/user/profile', methods=['GET', 'PUT'])
> @login_required
> def users():
>     return User.get_delete_put_post(request.current_user)
> ```
> 
> GET method: works perfectly
> PUT method: When I hit it, it fails

Apologies for not replying earlier.
