### ISSUE TITLE
fs_get_delete_put_post translates booleans incorrectly during PUT and POST Edits

### ISSUE THREAD

**Issue by Full-lifey** [Martlark/flask-serialize#43]
Writing a new endpoint and testing today I found an issue with booleans using the `fs_get_delete_put_post` method.

My model has an `active` boolean column. When I submit a PUT to update that column I correctly see the `False` value at the endpoint but once it gets submitted via `Model.fs_get_delete_put_post` I get this error:
```
(builtins.TypeError) Not a boolean value: 'n'
[SQL: UPDATE scenarios SET active=%(active)s, modified=%(modified)s WHERE scenarios.id = %(scenarios_id)s]
[parameters: [{'modified': datetime.datetime(2022, 1, 31, 21, 39, 28, 967404), 'active': 'n', 'scenarios_id': 5}]]
```

I resolved this issue by putting the below if.. elif inside the `__fs_verify__` method but it's not ideal.
```
  if self.active == 'y':
      self.active = True
  elif self.active == 'n':
      self.active = False
```

**Comment by Full-lifey** [comment]
I will likely have time to contribute a bit after deadlines at work. For now I'm reporting things I notice.

**Comment by Martlark** [comment]
The default conversion type for a boolean is to 'y' or 'n'


Conversion types when writing to database during update and create
------------------------------------------------------------------

Add or replace to db conversion methods by using a list of dicts that specify conversions for SQLAlchemy columns.

Default is:

.. code:: python

    __fs_convert_types__ = [{'type': bool, 'method': lambda v: 'y' if v else 'n'}]

**Comment by Martlark** [comment]
Using `__fs_verify__` is the preferred method of explicit type conversion.
eg:

     self.active = self.active == 'y

**Comment by Full-lifey** [comment]
Sounds good. Out of curiosity, which databases accept those values automatically? I'm using PostgreSQL.

Clear to close this as long as one of them supports that format by default.

**Comment by Full-lifey** [comment]
> Using `__fs_verify__` is the preferred method of explicit type conversion. eg:
> 
> ```
>  self.active = self.active == 'y'
> ```

Oooo, that's cleaner python too, thanks for the tips.
