### ISSUE TITLE
Could you give me example for  __fs_relationship_fields__

### ISSUE THREAD

**Issue by korykim** [Martlark/flask-serialize#45]
- Problem =》 "Error:\"'Role' object has no attribute 'fs_as_dict'\". Failed to convert [roles] type:RELATIONSHIP",
- error
```json
{
"comments": [],
"confirmed": false,
"confirmed_on": "",
"displayname": "jonesamanda",
"email": "mark62@example.org",
"id": 1,
"is_active": true,
"is_anonymous": false,
"is_authenticated": true,
"items": "Error:\"'Item' object has no attribute 'fs_as_dict'\". Failed to convert [items] type:RELATIONSHIP",
"locale": "",
"password": "",
"posts": [],
"roles": "Error:\"'Role' object has no attribute 'fs_as_dict'\". Failed to convert [roles] type:RELATIONSHIP",
"username": "jonesamanda"
},
```

**Comment by Martlark** [comment]
If you can paste in your model definitions I'll show you how the `__fs_relationship_fields__` is used.  But basically as follows in this example:

`  
class Setting(fs_mixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)

    setting_type = db.Column(db.String(120), index=True, default="misc")
    key = db.Column(db.String(120), index=True)
    value = db.Column(db.String(3000), default="")

    sub_settings = db.relationship(
        "SubSetting", backref="setting", cascade="all, delete-orphan"
    )
    single = db.relationship(
        "Single", backref="setting", uselist=False, cascade="all, delete-orphan"
    )

    __fs_relationship_fields__ = [sub_settings, "single"]
`

This will allow the `sub_settings` and `single` relationship to be serialized.

**Comment by Martlark** [comment]
NOTE: The child models must also use the Flask serialize mixin.
